num = int(input('Digite um número para ver sua tabuada: '))
num0 = num * 0
num1 = num * 1
num2 = num * 2
num3 = num * 3
num4 = num * 4
num5 = num * 5
num6 = num * 6
num7 = num * 7
num8 = num * 8
num9 = num * 9
num10 = num * 10
print('=' * 12)
print(f'{num} x {0:2}  = {num0}')
print(f'{num} x {1:2}  = {num1}')
print(f'{num} x {2:2}  = {num2}')
print(f'{num} x {3:2}  = {num3}')
print(f'{num} x {4:2}  = {num4}')
print(f'{num} x {5:2}  = {num5}')
print(f'{num} x {6:2}  = {num6}')
print(f'{num} x {7:2}  = {num7}')
print(f'{num} x {8:2}  = {num8}')
print(f'{num} x {9:2}  = {num9}')
print(f'{num} x {10:3} = {num10}')
print('=' * 12)
